// swiftlint:disable all
// Generated by SwiftUIColor (https://github.com/p-x9/SwiftUIColor)

import SwiftUI

public extension Color {
    enum tvOS {
        public static let tertiaryLabel = Color("tvOS/tertiaryLabel", bundle: .myModule)
        public static let systemRed = Color("tvOS/systemRed", bundle: .myModule)
        public static let systemPurple = Color("tvOS/systemPurple", bundle: .myModule)
        public static let systemIndigo = Color("tvOS/systemIndigo", bundle: .myModule)
        public static let systemGreen = Color("tvOS/systemGreen", bundle: .myModule)
        public static let systemPink = Color("tvOS/systemPink", bundle: .myModule)
        public static let placeholderText = Color("tvOS/placeholderText", bundle: .myModule)
        public static let link = Color("tvOS/link", bundle: .myModule)
        public static let systemGray = Color("tvOS/systemGray", bundle: .myModule)
        public static let secondaryLabel = Color("tvOS/secondaryLabel", bundle: .myModule)
        public static let systemOrange = Color("tvOS/systemOrange", bundle: .myModule)
        public static let separator = Color("tvOS/separator", bundle: .myModule)
        public static let quaternaryLabel = Color("tvOS/quaternaryLabel", bundle: .myModule)
        public static let systemBlue = Color("tvOS/systemBlue", bundle: .myModule)
        public static let tint = Color("tvOS/tint", bundle: .myModule)
        public static let systemCyan = Color("tvOS/systemCyan", bundle: .myModule)
        public static let systemYellow = Color("tvOS/systemYellow", bundle: .myModule)
        public static let systemBrown = Color("tvOS/systemBrown", bundle: .myModule)
        public static let opaqueSeparator = Color("tvOS/opaqueSeparator", bundle: .myModule)
        public static let label = Color("tvOS/label", bundle: .myModule)
        public static let systemMint = Color("tvOS/systemMint", bundle: .myModule)
        public static let systemTeal = Color("tvOS/systemTeal", bundle: .myModule)
    }
}

extension Color.tvOS {
    public static let colors = [tertiaryLabel, systemRed, systemPurple, systemIndigo, systemGreen, systemPink, placeholderText, link, systemGray, secondaryLabel, systemOrange, separator, quaternaryLabel, systemBlue, tint, systemCyan, systemYellow, systemBrown, opaqueSeparator, label, systemMint, systemTeal]

    public static let colorNames = ["tertiaryLabel", "systemRed", "systemPurple", "systemIndigo", "systemGreen", "systemPink", "placeholderText", "link", "systemGray", "secondaryLabel", "systemOrange", "separator", "quaternaryLabel", "systemBlue", "tint", "systemCyan", "systemYellow", "systemBrown", "opaqueSeparator", "label", "systemMint", "systemTeal"]
}
