// swiftlint:disable all
// Generated by SwiftUIColor (https://github.com/p-x9/SwiftUIColor)

import SwiftUI

public extension Color {
    enum watchOS {
        public static let tertiaryLabel = Color("watchOS/tertiaryLabel", bundle: .myModule)
        public static let systemRed = Color("watchOS/systemRed", bundle: .myModule)
        public static let systemPurple = Color("watchOS/systemPurple", bundle: .myModule)
        public static let systemIndigo = Color("watchOS/systemIndigo", bundle: .myModule)
        public static let systemGreen = Color("watchOS/systemGreen", bundle: .myModule)
        public static let systemPink = Color("watchOS/systemPink", bundle: .myModule)
        public static let systemGray = Color("watchOS/systemGray", bundle: .myModule)
        public static let secondaryLabel = Color("watchOS/secondaryLabel", bundle: .myModule)
        public static let systemOrange = Color("watchOS/systemOrange", bundle: .myModule)
        public static let quaternaryLabel = Color("watchOS/quaternaryLabel", bundle: .myModule)
        public static let systemBlue = Color("watchOS/systemBlue", bundle: .myModule)
        public static let systemCyan = Color("watchOS/systemCyan", bundle: .myModule)
        public static let systemYellow = Color("watchOS/systemYellow", bundle: .myModule)
        public static let systemBrown = Color("watchOS/systemBrown", bundle: .myModule)
        public static let label = Color("watchOS/label", bundle: .myModule)
        public static let systemMint = Color("watchOS/systemMint", bundle: .myModule)
        public static let systemTeal = Color("watchOS/systemTeal", bundle: .myModule)
    }
}

extension Color.watchOS {
    public static let colors = [tertiaryLabel, systemRed, systemPurple, systemIndigo, systemGreen, systemPink, systemGray, secondaryLabel, systemOrange, quaternaryLabel, systemBlue, systemCyan, systemYellow, systemBrown, label, systemMint, systemTeal]


    public static let colorNames = ["tertiaryLabel", "systemRed", "systemPurple", "systemIndigo", "systemGreen", "systemPink", "systemGray", "secondaryLabel", "systemOrange", "quaternaryLabel", "systemBlue", "systemCyan", "systemYellow", "systemBrown", "label", "systemMint", "systemTeal"]
}