// swiftlint:disable all
// Generated by SwiftUIColor (https://github.com/p-x9/SwiftUIColor)

import SwiftUI

public extension Color {
    enum tvOSConstant: String, CaseIterable {
        case tertiaryLabel
        case systemRed
        case systemPurple
        case systemIndigo
        case systemGreen
        case systemPink
        case placeholderText
        case link
        case systemGray
        case secondaryLabel
        case systemOrange
        case separator
        case quaternaryLabel
        case systemBlue
        case tint
        case systemCyan
        case systemYellow
        case systemBrown
        case opaqueSeparator
        case label
        case systemMint
        case systemTeal

        var name: String { rawValue }
    }
}

public extension Color {
    struct TvOS {
        public let tertiaryLabel = Color("tvOS/tertiaryLabel", bundle: .myModule)

        public let systemRed = Color("tvOS/systemRed", bundle: .myModule)

        public let systemPurple = Color("tvOS/systemPurple", bundle: .myModule)

        public let systemIndigo = Color("tvOS/systemIndigo", bundle: .myModule)

        public let systemGreen = Color("tvOS/systemGreen", bundle: .myModule)

        public let systemPink = Color("tvOS/systemPink", bundle: .myModule)

        public let placeholderText = Color("tvOS/placeholderText", bundle: .myModule)

        public let link = Color("tvOS/link", bundle: .myModule)

        public let systemGray = Color("tvOS/systemGray", bundle: .myModule)

        public let secondaryLabel = Color("tvOS/secondaryLabel", bundle: .myModule)

        public let systemOrange = Color("tvOS/systemOrange", bundle: .myModule)

        public let separator = Color("tvOS/separator", bundle: .myModule)

        public let quaternaryLabel = Color("tvOS/quaternaryLabel", bundle: .myModule)

        public let systemBlue = Color("tvOS/systemBlue", bundle: .myModule)

        public let tint = Color("tvOS/tint", bundle: .myModule)

        public let systemCyan = Color("tvOS/systemCyan", bundle: .myModule)

        public let systemYellow = Color("tvOS/systemYellow", bundle: .myModule)

        public let systemBrown = Color("tvOS/systemBrown", bundle: .myModule)

        public let opaqueSeparator = Color("tvOS/opaqueSeparator", bundle: .myModule)

        public let label = Color("tvOS/label", bundle: .myModule)

        public let systemMint = Color("tvOS/systemMint", bundle: .myModule)

        public let systemTeal = Color("tvOS/systemTeal", bundle: .myModule)
    }
}

public extension Color.TvOS {
    func callAsFunction(_ constant: Color.tvOSConstant) -> Color {
        Color("tvOS/\(constant.rawValue)", bundle: .myModule)
    }
}

public extension Color {
    static let tvOS = TvOS()
}

public extension Color.TvOS {
    var colors: [Color] {
        Color.tvOSConstant.allCases.map { Color.tvOS($0) }
    }

    var colorNames: [String] {
        Color.tvOSConstant.allCases.map { $0.name }
    }
}
