// swiftlint:disable all
// Generated by SwiftUIColor (https://github.com/p-x9/SwiftUIColor)

import SwiftUI

public extension Color {
    enum visionOS {
        public static let systemGroupedBackgroundColor = Color("visionOS/systemGroupedBackgroundColor", bundle: .myModule)
        public static let systemPinkColor = Color("visionOS/systemPinkColor", bundle: .myModule)
        public static let systemYellowColor = Color("visionOS/systemYellowColor", bundle: .myModule)
        public static let secondarySystemGroupedBackgroundColor = Color("visionOS/secondarySystemGroupedBackgroundColor", bundle: .myModule)
        public static let quaternarySystemFillColor = Color("visionOS/quaternarySystemFillColor", bundle: .myModule)
        public static let opaqueSeparatorColor = Color("visionOS/opaqueSeparatorColor", bundle: .myModule)
        public static let tertiarySystemBackgroundColor = Color("visionOS/tertiarySystemBackgroundColor", bundle: .myModule)
        public static let labelColor = Color("visionOS/labelColor", bundle: .myModule)
        public static let lightTextColor = Color("visionOS/lightTextColor", bundle: .myModule)
        public static let systemIndigoColor = Color("visionOS/systemIndigoColor", bundle: .myModule)
        public static let linkColor = Color("visionOS/linkColor", bundle: .myModule)
        public static let systemOrangeColor = Color("visionOS/systemOrangeColor", bundle: .myModule)
        public static let systemGray3Color = Color("visionOS/systemGray3Color", bundle: .myModule)
        public static let systemGray4Color = Color("visionOS/systemGray4Color", bundle: .myModule)
        public static let tertiaryLabelColor = Color("visionOS/tertiaryLabelColor", bundle: .myModule)
        public static let tertiarySystemGroupedBackgroundColor = Color("visionOS/tertiarySystemGroupedBackgroundColor", bundle: .myModule)
        public static let systemPurpleColor = Color("visionOS/systemPurpleColor", bundle: .myModule)
        public static let systemGray5Color = Color("visionOS/systemGray5Color", bundle: .myModule)
        public static let systemGrayColor = Color("visionOS/systemGrayColor", bundle: .myModule)
        public static let darkTextColor = Color("visionOS/darkTextColor", bundle: .myModule)
        public static let secondaryLabelColor = Color("visionOS/secondaryLabelColor", bundle: .myModule)
        public static let systemBackgroundColor = Color("visionOS/systemBackgroundColor", bundle: .myModule)
        public static let systemRedColor = Color("visionOS/systemRedColor", bundle: .myModule)
        public static let systemTealColor = Color("visionOS/systemTealColor", bundle: .myModule)
        public static let systemGray6Color = Color("visionOS/systemGray6Color", bundle: .myModule)
        public static let systemGray2Color = Color("visionOS/systemGray2Color", bundle: .myModule)
        public static let systemBlueColor = Color("visionOS/systemBlueColor", bundle: .myModule)
        public static let systemGreenColor = Color("visionOS/systemGreenColor", bundle: .myModule)
        public static let groupTableViewBackgroundColor = Color("visionOS/groupTableViewBackgroundColor", bundle: .myModule)
        public static let secondarySystemBackgroundColor = Color("visionOS/secondarySystemBackgroundColor", bundle: .myModule)
        public static let systemFillColor = Color("visionOS/systemFillColor", bundle: .myModule)
        public static let tintColor = Color("visionOS/tintColor", bundle: .myModule)
        public static let tertiarySystemFillColor = Color("visionOS/tertiarySystemFillColor", bundle: .myModule)
        public static let quaternaryLabelColor = Color("visionOS/quaternaryLabelColor", bundle: .myModule)
        public static let systemBrownColor = Color("visionOS/systemBrownColor", bundle: .myModule)
        public static let placeholderTextColor = Color("visionOS/placeholderTextColor", bundle: .myModule)
        public static let separatorColor = Color("visionOS/separatorColor", bundle: .myModule)
        public static let secondarySystemFillColor = Color("visionOS/secondarySystemFillColor", bundle: .myModule)
    }
}

extension Color.visionOS {
    public static let colors = [systemGroupedBackgroundColor, systemPinkColor, systemYellowColor, secondarySystemGroupedBackgroundColor, quaternarySystemFillColor, opaqueSeparatorColor, tertiarySystemBackgroundColor, labelColor, lightTextColor, systemIndigoColor, linkColor, systemOrangeColor, systemGray3Color, systemGray4Color, tertiaryLabelColor, tertiarySystemGroupedBackgroundColor, systemPurpleColor, systemGray5Color, systemGrayColor, darkTextColor, secondaryLabelColor, systemBackgroundColor, systemRedColor, systemTealColor, systemGray6Color, systemGray2Color, systemBlueColor, systemGreenColor, groupTableViewBackgroundColor, secondarySystemBackgroundColor, systemFillColor, tintColor, tertiarySystemFillColor, quaternaryLabelColor, systemBrownColor, placeholderTextColor, separatorColor, secondarySystemFillColor]

    public static let colorNames = ["systemGroupedBackgroundColor", "systemPinkColor", "systemYellowColor", "secondarySystemGroupedBackgroundColor", "quaternarySystemFillColor", "opaqueSeparatorColor", "tertiarySystemBackgroundColor", "labelColor", "lightTextColor", "systemIndigoColor", "linkColor", "systemOrangeColor", "systemGray3Color", "systemGray4Color", "tertiaryLabelColor", "tertiarySystemGroupedBackgroundColor", "systemPurpleColor", "systemGray5Color", "systemGrayColor", "darkTextColor", "secondaryLabelColor", "systemBackgroundColor", "systemRedColor", "systemTealColor", "systemGray6Color", "systemGray2Color", "systemBlueColor", "systemGreenColor", "groupTableViewBackgroundColor", "secondarySystemBackgroundColor", "systemFillColor", "tintColor", "tertiarySystemFillColor", "quaternaryLabelColor", "systemBrownColor", "placeholderTextColor", "separatorColor", "secondarySystemFillColor"]
}
