// swiftlint:disable all
// Generated by SwiftUIColor (https://github.com/p-x9/SwiftUIColor)

import SwiftUI

public extension Color {
    enum universal {
        public static let tertiaryLabel = Color("universal/tertiaryLabel", bundle: .myModule)
        public static let systemRed = Color("universal/systemRed", bundle: .myModule)
        public static let systemPurple = Color("universal/systemPurple", bundle: .myModule)
        public static let systemIndigo = Color("universal/systemIndigo", bundle: .myModule)
        public static let systemGreen = Color("universal/systemGreen", bundle: .myModule)
        public static let systemPink = Color("universal/systemPink", bundle: .myModule)
        public static let systemGray = Color("universal/systemGray", bundle: .myModule)
        public static let secondaryLabel = Color("universal/secondaryLabel", bundle: .myModule)
        public static let systemOrange = Color("universal/systemOrange", bundle: .myModule)
        public static let quaternaryLabel = Color("universal/quaternaryLabel", bundle: .myModule)
        public static let systemBlue = Color("universal/systemBlue", bundle: .myModule)
        public static let systemCyan = Color("universal/systemCyan", bundle: .myModule)
        public static let systemYellow = Color("universal/systemYellow", bundle: .myModule)
        public static let systemBrown = Color("universal/systemBrown", bundle: .myModule)
        public static let label = Color("universal/label", bundle: .myModule)
        public static let systemMint = Color("universal/systemMint", bundle: .myModule)
        public static let systemTeal = Color("universal/systemTeal", bundle: .myModule)
    }
}

extension Color.universal {
    public static let colors = [tertiaryLabel, systemRed, systemPurple, systemIndigo, systemGreen, systemPink, systemGray, secondaryLabel, systemOrange, quaternaryLabel, systemBlue, systemCyan, systemYellow, systemBrown, label, systemMint, systemTeal]


    public static let colorNames = ["tertiaryLabel", "systemRed", "systemPurple", "systemIndigo", "systemGreen", "systemPink", "systemGray", "secondaryLabel", "systemOrange", "quaternaryLabel", "systemBlue", "systemCyan", "systemYellow", "systemBrown", "label", "systemMint", "systemTeal"]
}